# -*- coding: utf-8 -*-
"""asiignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vO_5MDM3PW1Hq_NDCmMnbIUDd5jsRjjU
"""

!pip install dnspython
!pip install pymongo[srv]
!pip install qrcode[pil]
! python -m pip install pymongo==3.7.2

"""*RZtqQj3KrsssTYXM* *italicized text* *italicized text*"""



import pymongo
from pymongo import MongoClient


client = pymongo.MongoClient("mongodb+srv://vinothsevugan:RZtqQj3KrsssTYXM@cluster0.owkmn.mongodb.net/user?retryWrites=true&w=majority")

db = client.user 
records=db.movies

movies={"_id":1,"Movie":"Spider Man","Seat Availability":100,"CBFC Rating":"U/A"},{"_id":2,"Movie":"Pushpa","Seat Availability":100,"CBFC Rating":"A"},{"_id":3,"Movie":"Valimai","Seat Availability":100,"CBFC Rating":"U"},{"_id":4,"Movie":"Beast","Seat Availability":100,"CBFC Rating":"U/A"},{"_id":5,"Movie":"KGF 2","Seat Availability":100,"CBFC Rating":"U/A"}

records.insert_many(movies)

theat=db.Theatre

th1={"_id":1,"Theatre Name":"Inox"},{"_id":2,"Theatre Name":"PVR"}

theat.insert_many(th1)

timings=db.time

t1={"_id":1,"Time":"11.30"},{"_id":2,"Time":"03.30"},{"_id":3,"Time":"05.30"}

timings.insert_many(t1)

import pandas as pd
data = pd.DataFrame(list(records.find()))
print(data)

for x in records.find():
  print(x)



records.insert_one(new2)



db = client.user 
rec=db.userlists
def Register():
  name1=input("Enter Your Name")
  email1=input("Enter your Email")
  phone1=int(input("Enter your Phone no"))
  password1=input("Enter Password")
  myuser1={
    "name":name1,
    "email":email1,
    "phone":phone1,
    "password":password1}
  rec.insert_one(myuser1)

def login():
  email1=input("Enter your Email")
  password1=input("Enter Password")
  
  v={"email":email1,"password":password1}
  
  name1=[]
  mydoc=rec.find(v,{"_id":1,"name":1,"email":1,"password":1})
  for i in mydoc:
    name1=i.get("name")
  print("Welcome",name1) 
  if name1 is NULL:
    print("Name not Found Please register yourself")
    Register()
  else:
    Selection(name1)

login()

import random
import qrcode
import matplotlib.pyplot as plt
import pandas as pd
def Selection(name):
  
  data = pd.DataFrame(list(records.find()))
  print(data)
  msel=int(input("Please select the movie "))
  
  v1={"_id":msel}
  xx1=[]
  mydoc2=records.find(v1,{"_id":1,"Movie":1})
  for i in mydoc2:
    xx1=i.get("Movie") 

  x,xx,xxx=theater()
  print("          Guvi Cinemas")
  print("Hooray Ticket Booked for ",name)
  print("Movie Name,",xx1)
  print("Theater",x)
  print("Time,",xx)
  print("No of Persons",xxx)
  seat=[]
  for i in range(xxx):
    seat.append(random.randint(0,100))
  print("Seat Number ",*seat)  
  recre=db.booked
  mydict={"name1":name,
          "Movie name":xx1,
          "Theater":x,
          "Time":xx,
          "Persons":xxx,
          "Seat No":seat}
  recre.insert_one(mydict)
  
  
  img = qrcode.make(mydict)
  type(img)  
  img.save("some_file.png")
  from PIL import Image
  
  im=Image.open("some_file.png")
  plt.imshow(img)
  plt.show()

def theater():
  data = pd.DataFrame(list(theat.find()))     ###need to change to theater list
  print(data)

  print("please select the theater")
  n=int(input())
  v1={"_id":n}
  xx1=[]
  mydoc2=theat.find(v1,{"_id":1,"Theatre Name":1})
  for i in mydoc2:
    xx1=i.get("Theatre Name")
  data = pd.DataFrame(list(timings.find()))     ###need to change to theater timings
  print(data)
  print("enter theater timings")
  ti=int(input())
  v2={"_id":ti}
  xxx1=[]
  mydoc1=timings.find(v2,{"_id":1,"Time":1})
  for i in mydoc1:
    xxx1=i.get("Time")
  print("enter number of persons")
  persons=int(input())
  myquery={"_id":n}
  update={"$inc":{"Seat Availability":-persons}}
  records.update_one(myquery,update)
  return (xx1,xxx1,persons)

def display(name):
  v={"name1":name}
  recre=db.booked
  
  for x in recre.find(v,{"_id":1,"Movie name":1,"Theater":1,"Time":1,"Seat No":1}):
    print(x)



print("Enter   1 to login \n \t2 to Register \n \t3 To display ticket")
a=int(input())
if a==1:
  login()
elif a==2:
  Register()
 elif a==3:
   print("Enter User name")
   user=input()
   display(user)
 else:
   print("Wrong Number")